### ISSUE TITLE
This class is not found in the file

### ISSUE THREAD

**Issue by HuskyFly** [youssef-fk/flutter_traceroute#1]
This class is not found in the file 
![image](https://user-images.githubusercontent.com/23441922/204278222-3dddc791-8a17-480f-9422-5feb596bf793.png)

**Comment by youssef-fk** [comment]
Can you confirm you have up the `Podfile` to include

`platform :ios, '14.0'`

And

```
pod 'SimplePing', :git => 'https://github.com/youssef-fk/SimplePing.git'
pod 'SimpleTracer', :git => 'https://github.com/youssef-fk/SimpleTracer.git'
```

Then run `pod install` on the ios folder ?
